### ISSUE TITLE
Delegate Action encoded by near-api-js throws Ledger transport error

### ISSUE THREAD

**Issue by lostpebble** [LedgerHQ/app-near#9]
Hi- I'm testing out Delegate Action signing using the new Near Ledger app, coming from the `@near-js/transactions` library, where a Delegate Action is encoded using `encodeDelegateAction(delegateAction)`, found here:

https://github.com/near/near-api-js/blob/bc78d21f472f0fe31a02b2897a1409787dbb1188/packages/transactions/src/schema.ts#L18

Using the same test data from the NEP413 test in this repo: https://github.com/LedgerHQ/app-near-new/blob/9223ab208cbb79cd3e2ca48e29906c4102f25c0d/tests/test_sign_nep366_delegate_action/test_nep366_delegate_action.py#L15

to construct the Delegate Action in JavaScript:

```tsx
const usedPublicKey = "ed25519:EFr6nRvgKKeteKoEH7hudt8UHYiu94Liq2yMM7x2AU9U";

const delegateAction = buildDelegateAction({
  senderId: "bob.near",
  receiverId: "alice.near",
  actions: [actionCreators.transfer(BigInt("150000000000000000000000"))],
  maxBlockHeight: BigInt(100500),
  nonce: BigInt(127127122121),
  publicKey: PublicKey.fromString(usedPublicKey),
});
```

I encode the Delegate Action and get the hex to compare with the one in your test set, like so:

```tsx
const encodedDelegate = encodeDelegateAction(delegateAction);
const encodedDelegateHex = Buffer.from(encodedDelegate).toString("hex");
```

And then I compare the hex string data, removing the initial APDU bytes and the `hdpath` prefix of the data, I get a direct comparison of the encoded Delegate Action data like this:

```tsx
Encoding from JS Near lib    : 6e01004008000000626f622e6e6561720a000000616c6963652e6e65617201000000030000c071f0d12b84c31f000000000000c9f05d991d000000948801000000000000c4f5941e81e071c2fd1dae2e71fd3d859d462484391d9a90bf219211dcbb320f
Encoding in Near Ledger test :         08000000626f622e6e6561720a000000616c6963652e6e65617201000000030000c071f0d12b84c31f000000000000c9f05d991d000000948801000000000000c4f5941e81e071c2fd1dae2e71fd3d859d462484391d9a90bf219211dcbb320f
```

As you can see there are 4 bytes more in the one from the Near API JS library.

I am unsure if this is an issue with the JS library, or with the Ledger implementation. But if I try and send this data (correctly formatted including the HD Path prefix)- it throws an error straight away. So something is misaligned here.

I have Sign Message (NEP413) and Sign Transaction working great with the new app, so its not a matter of interfacing incorrectly.

If I cut away those first 4 bytes in the encoded Delegate Action data, the Ledger works and responds, but I can’t verify the signature returned from the Ledger (trying with both the original and the 4-bytes-less encoded hash).

We have successfully been signing and relaying delegate actions on the Near network using the JS libraries, so I think there might be something wrong with the Ledger implementation?

**Comment by dj8yfo** [comment]
@lostpebble the 4 bytes are prefix ( 1 << 30 +366 ) reversed (little endian), which get prepended to the message payload on device. You might want to try adjust signature verification logic to account for (prefix + msg) is being signed, not (msg) or (prefix + prefix + msg)

**Comment by lostpebble** [comment]
@dj8yfo I am using the official Near library to encode the Delegate Action though- so surely this should be encoded correctly the first time with the prefix?

If you look at their code, it includes some kind of prefix encoding:

```ts
export function encodeDelegateAction(delegateAction: DelegateAction) {
    return new Uint8Array([
        ...serialize(SCHEMA.DelegateActionPrefix, new DelegateActionPrefix()),
        ...serialize(SCHEMA.DelegateAction, delegateAction),
    ]);
}
```

So perhaps they are doing it incorrectly? But using the JS library has been working fine for us in the past for actually signing and sending signed delegates on the blockchain to be executed (we don't control signature verification on-chain, of course), so that's why I found it strange. I'll try add the prefix data as you mentioned, and test out sending the signed delegate on the blockchain.

**Comment by dj8yfo** [comment]
The prefix get's added on device.
If you add one more, the signed message will be (prefix + prefix + delegate_action), that will be incorrect.

You should send (delegate_action) to device and verify , that (prefix + delegate_action) have been signed

**Comment by lostpebble** [comment]
> The prefix get's added on device. If you add one more, the signed message will be (prefix + prefix + delegate_action), that will be incorrect.
> 
> You should send (delegate_action) to device and verify , that (prefix + delegate_action) have been signed

But what I've been talking about is the data as given to us from the Near JS library- before anything has been sent to the device. The tests in this repo send data with even more bytes than what is in the Near JS library gives- so this statement confuses me a bit.

Are you saying that we must only use the part of the code inside the NEAR JS library that doesn't use the prefix?:

```ts
const sendBytesToLedger = serialize(SCHEMA.DelegateAction, delegateAction);
```

I'm going to test and see.

**Comment by lostpebble** [comment]
Okay, using the pure:

```ts
const sendBytesToLedger = serialize(SCHEMA.DelegateAction, delegateAction);
```

Worked well. Thanks for the help. So the crux of it is that we must always just send the pure encoded payload without prefixes to the Ledger device- it will take care of the prefix part.

Think it could be good to document this stuff, especially with some kind of example repo with code.
